-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-06 20:18:59 BRST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE AMIZADE;
DROP TABLE COMENTARIO;
DROP TABLE REACAO;
DROP TABLE POSTAGEM;
DROP TABLE USUARIO;


CREATE TABLE amizade (
    id               INTEGER NOT NULL,
    status           VARCHAR2(20) DEFAULT 'ATIVA' NOT NULL,
    id_solicitante   INTEGER NOT NULL,
    id_solicitado    INTEGER NOT NULL
);

ALTER TABLE amizade ADD CONSTRAINT amizade_pk PRIMARY KEY ( id );

CREATE TABLE comentario (
    id            INTEGER NOT NULL,
    data_hora     DATE NOT NULL,
    descricao     VARCHAR2(255) NOT NULL,
    id_postagem   INTEGER NOT NULL,
    id_usuario    INTEGER NOT NULL
);

ALTER TABLE comentario ADD CONSTRAINT comentario_pk PRIMARY KEY ( id );

CREATE TABLE postagem (
    id            INTEGER NOT NULL,
    titulo        VARCHAR2(255) NOT NULL,
    data_hora     DATE NOT NULL,
    imagem        VARCHAR2(512),
    descricao     VARCHAR2(512),
    privacidade   VARCHAR2(20) NOT NULL,
    id_usuario    INTEGER NOT NULL
);

ALTER TABLE postagem ADD CONSTRAINT postagem_pk PRIMARY KEY ( id );

CREATE TABLE reacao (
    id            INTEGER NOT NULL,
    data_hora     DATE NOT NULL,
    id_usuario    INTEGER NOT NULL,
    id_postagem   INTEGER NOT NULL
);

ALTER TABLE reacao ADD CONSTRAINT reacao_pk PRIMARY KEY ( id );

CREATE TABLE usuario (
    id                INTEGER NOT NULL,
    nome_completo     VARCHAR2(255) NOT NULL,
    email             VARCHAR2(255) NOT NULL,
    apelido           VARCHAR2(50),
    data_nascimento   DATE NOT NULL,
    senha             VARCHAR2(128) NOT NULL,
    imagem_perfil     VARCHAR2(512)
);

ALTER TABLE usuario ADD CONSTRAINT usuario_pk PRIMARY KEY ( id );

ALTER TABLE usuario ADD CONSTRAINT usuario__un UNIQUE ( email );

ALTER TABLE amizade
    ADD CONSTRAINT amizade_usuario_fk FOREIGN KEY ( id_solicitante )
        REFERENCES usuario ( id );

ALTER TABLE amizade
    ADD CONSTRAINT amizade_usuario_fkv2 FOREIGN KEY ( id_solicitado )
        REFERENCES usuario ( id );

ALTER TABLE comentario
    ADD CONSTRAINT comentario_postagem_fk FOREIGN KEY ( id_postagem )
        REFERENCES postagem ( id );

ALTER TABLE comentario
    ADD CONSTRAINT comentario_usuario_fk FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );

ALTER TABLE postagem
    ADD CONSTRAINT postagem_usuario_fk FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );

ALTER TABLE reacao
    ADD CONSTRAINT reacao_postagem_fk FOREIGN KEY ( id_postagem )
        REFERENCES postagem ( id );

ALTER TABLE reacao
    ADD CONSTRAINT reacao_usuario_fk FOREIGN KEY ( id_usuario )
        REFERENCES usuario ( id );


DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_AMIZADE;
DROP SEQUENCE SEQ_POSTAGEM;
DROP SEQUENCE SEQ_COMENTARIO;
DROP SEQUENCE SEQ_REACAO;

CREATE SEQUENCE SEQ_USUARIO NOCACHE;
CREATE SEQUENCE SEQ_AMIZADE NOCACHE;
CREATE SEQUENCE SEQ_POSTAGEM NOCACHE;
CREATE SEQUENCE SEQ_COMENTARIO NOCACHE;
CREATE SEQUENCE SEQ_REACAO NOCACHE;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
